export * from './IAuth';
export * from './ICabinet';
export * from './IClient';
export * from './IClinic';
export * from './IDoctor';
export * from './IDutyShift';
export * from './IEvents';
export * from './IPriceList';
export * from './IProfile';
